# Generated by Django 3.2.6 on 2021-08-16 06:28

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', django.contrib.postgres.fields.citext.CICharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/%Y/%m/%d/', verbose_name='Изображение')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='PGSRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', django.contrib.postgres.fields.citext.CICharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Anime_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', django.contrib.postgres.fields.citext.CICharField(max_length=250, verbose_name='Имя на русском')),
                ('name_eng', django.contrib.postgres.fields.citext.CICharField(max_length=250, verbose_name='Имя на английском')),
                ('rating', django.contrib.postgres.fields.citext.CICharField(max_length=50, null=True, verbose_name='Рейтинг')),
                ('status', django.contrib.postgres.fields.citext.CICharField(choices=[('Announcement', 'Анонсировано'), ('Ongoing', 'Выходит'), ('Released', 'Вышло')], max_length=50, verbose_name='Статус')),
                ('release_date', django.contrib.postgres.fields.citext.CICharField(max_length=50, null=True, verbose_name='Дата выхода')),
                ('num_of_episodes', django.contrib.postgres.fields.citext.CICharField(max_length=50, null=True, verbose_name='Кол-во эпизодов')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='date published')),
                ('extent', models.SmallIntegerField(choices=[(1, 'Отвратительно'), (2, 'Ужасно'), (3, 'Неприемлимо'), (4, 'Плохо'), (5, 'Средне'), (6, 'Пойдет'), (7, 'Хорошо'), (8, 'Отлично'), (9, 'Великолепно'), (10, 'АААА ДАА')], default=5)),
                ('genre', models.ManyToManyField(to='catalog.Genres')),
            ],
            options={
                'verbose_name': 'Тайтл',
                'verbose_name_plural': 'Тайтлы',
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.AddIndex(
            model_name='anime_title',
            index=models.Index(fields=['rating', 'status', 'release_date'], name='anime_title_main'),
        ),
        migrations.AddIndex(
            model_name='anime_title',
            index=models.Index(fields=['name_ru', 'rating', 'num_of_episodes'], name='anime_title_second'),
        ),
    ]
