# Generated by Django 3.2.3 on 2021-05-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=250)),
                ('name_jp', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=50)),
                ('num_of_episodes', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
