# Generated by Django 3.2.6 on 2021-08-08 07:10

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', django.contrib.postgres.fields.citext.CICharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.RemoveField(
            model_name='anime_title',
            name='genre',
        ),
        migrations.AddField(
            model_name='anime_title',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genres'),
        ),
    ]
