# Generated by Django 3.2.3 on 2021-06-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210531_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime_title',
            name='genre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='num_of_episodes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='release_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='status',
            field=models.CharField(choices=[('Announcement', 'Анонсировано'), ('Ongoing', 'Выходит'), ('Released', 'Вышло')], max_length=50),
        ),
    ]
