# Generated by Django 3.2.3 on 2021-06-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210601_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime_title',
            options={'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.AddField(
            model_name='anime_title',
            name='extent',
            field=models.SmallIntegerField(choices=[(1, 'Отвратительно'), (2, 'Ужасно'), (3, 'Неприемлимо'), (4, 'Плохо'), (5, 'Средне'), (6, 'Пойдет'), (7, 'Хорошо'), (8, 'Отлично'), (9, 'Великолепно'), (10, 'Иди нахуй с такими оценками')], default=5),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='genre',
            field=models.CharField(max_length=250, null=True, verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='name_eng',
            field=models.CharField(max_length=250, verbose_name='Имя на английском'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='name_ru',
            field=models.CharField(max_length=250, verbose_name='Имя на русском'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='num_of_episodes',
            field=models.CharField(max_length=50, null=True, verbose_name='Кол-во эпизодов'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='rating',
            field=models.CharField(max_length=50, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='release_date',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='anime_title',
            name='status',
            field=models.CharField(choices=[('Announcement', 'Анонсировано'), ('Ongoing', 'Выходит'), ('Released', 'Вышло')], max_length=50, verbose_name='Статус'),
        ),
    ]
