# Generated by Django 3.2.3 on 2021-06-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210603_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='anime_title',
            options={'get_latest_by': 'pub_date', 'verbose_name': 'Тайтл', 'verbose_name_plural': 'Тайтлы'},
        ),
        migrations.RemoveField(
            model_name='anime_title',
            name='genre',
        ),
        migrations.AddIndex(
            model_name='anime_title',
            index=models.Index(fields=['rating', 'status', 'release_date'], name='anime_title_main'),
        ),
        migrations.AddIndex(
            model_name='anime_title',
            index=models.Index(fields=['name_ru', 'rating', 'num_of_episodes'], name='anime_title_second'),
        ),
        migrations.AddField(
            model_name='anime_title',
            name='genre',
            field=models.ManyToManyField(to='catalog.Genres'),
        ),
    ]
